### ISSUE TITLE
关于AMD黑果docker的使用

### ISSUE THREAD

**Issue by akwangl** [whidy/ASUS-PRIME-X570-PRO-Hackintosh#2]
楼主你好，我是看到一片关于[AMD黑苹果无法使用Docker的解决办法](https://www.whidy.net/amd-hackintosh-incompatible-docker-desktop-and-solution)来的，好像virtualbox7.x就没办法结合[minikube](https://minikube.sigs.k8s.io/)使用docker了，只能用6.1，再更高的mac13有尝试过解决docker的运行问题吗

**Comment by whidy** [comment]
兄弟，很遗憾，我近一两年都没有在hackintosh下折腾虚拟化技术所支持的应用了，因为问题太多了，可能是去年我在用docker的时候出现了一些其他难以解决的问题后（好像是安卓虚拟机如何配置，BIOS已正确配置，都无法正常使用），我就放弃了，所以之前的方案可能在某块需要应用的虚拟化技术上能兼容，但是总是会出现其他的问题。

所以我最后还是放弃了在AMD平台上的黑苹果虚拟化技术支持的深入研究了。

**Comment by akwangl** [comment]
我都打算买一台ARM小主机装armbian上搭一套编译环境了
